set_property SRC_FILE_INFO {cfile:C:/Users/aiai/Desktop/study/FPGA/Xlinx/2020_12_5/oled_test/oled/oled.srcs/constrs_1/new/LED.xdc rfile:../../../oled.srcs/constrs_1/new/LED.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {LED_0[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {LED_0[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {GPIO_0_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {GPIO_0_0_tri_io[0]}]
